### ISSUE TITLE
Solax instead of Shell 3EM

### ISSUE THREAD

**Issue by virility0** [thomase1234/esphome-fake-xemex-csmb#12]
Hi Thomase1234,

I am currently trying to copy your project and am almost done :)

As I use a QCell/Solax System, I already have all necessary data in my homeassistant (house load, pv production, energy export etc.pp). I am now recoding the automatisation, but I am not sure what these 3 parameters stand for:

shell3em_main_current
shell3em_main_power_factor
shelly3em_laadpaal_current

Could you shortly explain ? As far as I understood you measure the pv export with the Shelly3EM, right? Main current is what your house uses, right? For what do you use the power factor? Afaik my system already gives corrected data. In this case I could delete this part?

Thanks for your help

**Comment by thomase1234** [comment]
Hi @virility0 ,
Thanks for reaching out.

The sensors are indeed created by a Shelly3EM.

shell3em_main_current is the current on my cable between grid and house. This number is always positive, even if my house ( thanks to the pv - solar panels ) is producing more electricity than it consumes. If it reads 5 Amp, it can be that my house is consuming 5 Amp from the grid, or it can be that my house is delivering 5 Amp to the grid.

shell3em_main_power_factor is the power factor which ranges between -1 and 1. If the number is negative, that means that my house is producing more energy than it consumes which means that the excess energy is delivered to the grid. If the number is positive, the house is consuming from the grid. Usually the value is either very close to 1 when consuming, or very close to -1 when delivering to the grid.

Multiplying the 2 previous parameters give me a single number with the total of Amps consumed. Negative numbers for delivering. 

shelly3em_laadpaal_current is the current on the "laadpaal". "Laadpaal" is Dutch for Wall Charger. Since I know that the Wall Charger will always consume energy, I didn't multiply the number with its corresponding power_factor.

I hope this answers your questions. If not, let me know.

Best regards,
Thomas

**Comment by thomase1234** [comment]
I've included this info in the README

**Comment by virility0** [comment]
Hi Thomas, 
thank you very much for you explanation, it helps a lot?

Do you have a separate Shelly 3em to get specific values for "shelly3em_laadpaal_current"? I'll have to think about a work around for this as I have to work with the data from smart meter in my Solax system.
I cannot measure the current of the wallbox separately.

Regards

**Comment by thomase1234** [comment]
Hi @virility0 

Yes, I have a separate CT clamp on the wire to the wallcharger. The Shell 3EM comes with 3 CT clamps which can be used independently on different wires, or on a 3 phase connection. That doesn't really matter.

Yes, you'll need a way to measure the current consuming of the wallbox. It can be done by measuring it, like I did. Other people used the physical network connection inside their Shell Recharge to read the values from a built-in webserver. See [here](https://community.home-assistant.io/t/my-new-motion-integration-ev-charging-from-shell-newmotion/369593/111).

Yes, if you have a 3 phase connection, you'll have to adjust the CT1 CT2 and CT3 values separately and independently as you'll still want to make sure that you're not overloading a single phase.

f.e suppose each phase is max 16 Amps.
you measure 3Amp on phase 1 -> adjust CT1 to use remaining 13 Amps.
you measure 6Amp on phase 2 -> adjust CT2 to use remaining 10 Amps.
you measure 1Amp on phase 3 -> adjust CT3 to use remaining 15 Amps.

**Comment by virility0** [comment]
When I connect the TTL RS485 to the charger, do I also have to connect + and - besides A & B?

**Comment by thomase1234** [comment]
No, that's not required. Only A and B is required.

**Comment by virility0** [comment]
Nope...nothing...I think the Modbus is not active 👎 . No idea what to do now as the shell support told me they won't activate it. The only solution is that I find an electrician who kind of lies to them

**Comment by thomase1234** [comment]
If you put the original A and B wiring between WallCharger and DPM module back in place, does EVSE LED on the DPM module light up ? If yes, the Wall Charger is reading values over modbus protocol.
If not, they Wall Charger should be configured by Shell to use DPM. 

It's kinda strange that they install a DPM in your electricity closet without configuring the WallCharger to use it. Seems kinda pointless to me.

**Comment by virility0** [comment]
Oh no, there is a misunderstanding! 
I've never used an original DPM , that's why it's not activated. 

With your solution the original DPM is not required, therefore I did not buy it. And as I habe a 3 Phase 35A grid connection, I really don't need it. The highest usage ist about 16A per phase, so there is a large buffer

**Comment by thomase1234** [comment]
> Oh no, there is a misunderstanding! I've never used an original DPM , that's why it's not activated.
> 
> With your solution the original DPM is not required, therefore I did not buy it. And as I habe a 3 Phase 35A grid connection, I really don't need it. The highest usage ist about 16A per phase, so there is a large buffer

Aha, I understand it now. Thanks for clarifying and good luck getting Shell to enable the functionality.

**Comment by virility0** [comment]
So ...short update.

DPM is activated, automatization is working awesome in 1phase mode with my 1phase cable

 But with my 3 phase cable I cannot really regulate the charging power.
It should be able between 8A and 16A, but if the limit is below e.g. 14A, the charger automatically reduces it to 13A...12A...10A...8A..7A and the charging stops.

Is there any one who could test with a 3 phase connection?

**Comment by MisterAtoZ** [comment]
Hi @thomase1234 and @virility0,

I seem to have a similar issue. I created a [new issue](https://github.com/thomase1234/esphome-fake-xemex-csmb/issues/17) about this topic, as it doesn't really seem to fit in this thread.

**Comment by thomase1234** [comment]
Closing after inactivity
