### ISSUE TITLE
Power correction automation not working correctly

### ISSUE THREAD

**Issue by blvermeu** [thomase1234/esphome-fake-xemex-csmb#13]
Hi Thomas,

Small question here, I've just updated to your latest automation.yaml, but after modyfying this one with my own sensors, my regulation did not function properly anymore (it did with your older, more elaborate power correction automation).

For example, if i select solar only, and hit the start charging button, i see the CT3 value is going quickly up, which causes the shell charger to stop ( because the power he can take ends up below 8-9A).  When I look at part of the automation that is causing this (see below), it's kind logical:

`conditions:
  - condition: template
    value_template: >-
      {{(states('input_number.chargepoint_desired_current') | float(1) -
      (states('sensor.eastron_current_laadpaal') |float(1) ) ) > 0 }}  
sequence:
  - service: number.set_value
    data:
      value: >-
        {{ states('input_number.main_maximal_current') | float(1) -
        (states('input_number.chargepoint_desired_current') | float(1) -
        (states('sensor.eastron_current_laadpaal') |float(1) ) )}}
    target:
      entity_id: number.modbusservernaarlaadpaal_esp32_ct3current`

Any ideas on how to solve this? I'm kinda thinking of simplifying this bit alot and just take out the regulation and just go with:
`  - service: number.set_value
    data:
      value: >-
        {{ states('input_number.main_maximal_current') | float(1) -
        (states('input_number.chargepoint_desired_current') | float(1) )}}
    target:
      entity_id: number.modbusservernaarlaadpaal_esp32_ct3current`

Thanks a lot

Kind regards,

Ben

**Comment by thomase1234** [comment]
Hi Ben,

The previous Automation was not supposed to work correctly and since I don't know if/when Shell was going to fix that by updating the firmware in their ShellRecharge WallCharger, I decided to go ahead and stop relying on unexpected/unintented behaviour. Normally for a monophase connection, it should not use the values of CT3, and only use the values of CT1. That means, the Automation is not using CT3 anymore.

The new Automation works by simulation a load on the CT1. I assume you have a monophase grid connection.
First of all, you need to know which value to use on input_number.main_maximal_current
Suppose your input_number.main_maximal_current is set to 38Amp. If the Automation determines that 16 Amps can be used by the WallCharger, the CT1 would be set to 38 - 16 = 18 . After a few seconds the WallCharger will be using the 16 Amps and in order to make sure the WallCharger is not going to increase or decrease the charging speed, the CT1 would be set to 38Amp.
If the Automation determines that the Charging consumes to much power, he'll set CT1 to a value higher than 38Amp.

Conclusion : it's critical to know what value is configured on your WallCharger. My grid connection is secured with a 40Amp fuse. The Shell engineer configured 38Amps in order to have a safe margin.

You can determine the value for your WallCharger by following this procedure.

1. Connect your car to the WallCharger
2. Disable the Automation.
3. Browse to the webserver of the ESP32 modbusservernaarlaadpaal
4. set the value of CT1 to 8Amp
5. At this point your car should certainly be charging very fast.
6. Increase the CT1 with 1 Amp using the webserver.
7. Wait a few seconds to see the result on the Chargespeed
8. If the ChargingSpeed didn't change, go back to 6 and increase the CT1 value
9. If the ChargingSpeed went down, you have the load at which point the Charger thinks he is consuming too much current. 
10. Set the value in input_number.main_maximal_current
11. Re-enable the Automation is see if it works.

**Comment by blvermeu** [comment]
Hi Thomas,

Thanks for the quick reply!

I think I more or less grabbed the basic idea of modulating the load on the CT1 or CT3 (my charger still relies on CT3 as when i tried CT1 it did not respond).

To be honest, I think my situation is almost idential to yours (also 40 amp available, also living in belgium etc). And my maximal load will also be somewhere between 35 and 40 AMP.  I will use your procedure to check the exaxt maximum.

I do not understand this part of your aswer though:

> Suppose your input_number.main_maximal_current is set to 38Amp. If the Automation determines that 16 Amps can be used by the WallCharger, the CT1 would be set to 38 - 16 = 18 . After a few seconds the WallCharger will be using the 16 Amps and in order to make sure the WallCharger is not going to increase or decrease the charging speed, the CT1 would be set to 38Amp.
If the Automation determines that the Charging consumes to much power, he'll set CT1 to a value higher than 38Amp.

I was looking at all the values when running the automation while charging (low load, solar only => 10-12 AMPs).

what i see is that the CT3 values is around 27 in base mode (taking into account a max load of 37 AMPS and 10 AMPS of desired current). however when the charging starts, the effective current obviously goes up (also to around 10 AMPS), and the CT3 values goes up back up to 37, thereby effectivly crashing the charger (the load goes under the treshold of 8-9 AMPS).
this makes sense as this part of the automation 

`{{ states('input_number.main_maximal_current') | float(1) -
(states('input_number.chargepoint_desired_current') | float(1) -
(states('sensor.eastron_current_laadpaal') |float(1) ) )}}`

will give : 37 - (10-10) = 37

I don't know if have expressed the issue clear enough, but this will always crash the charger no? also with yourself, if your CT1 value is set to 38 or higher, this should also crash your charger?

Thanks for the help and elucidation!

Kind regards,

Ben

**Comment by thomase1234** [comment]
I'm not sure why you're still using the CT3 values. Leave CT2 and CT3 alone and only use CT1 for a monophase grid and charger setup.

> will give : 37 - (10-10) = 37
> 
> I don't know if have expressed the issue clear enough, but this will always crash the charger no? also with yourself, if your CT1
> value is set to 38 or higher, this should also crash your charger?

What do you mean with "crash" your charger? 

If my CT1 value goes higher than 38, the charging speed will decrease. That's expected behavior. 

If you think about it, that's also how the Shell Supplied DLM module will work. It'll report the actual load on your grid connection. That's the sum of your house + charger.
